DSEG SEGMENT;数据段
	STRING1 DB '123456789$'
	STRING2 DB '123456789$'
	MATCHSTR DB 'MATCH$'
	NOMATCHSTR DB 'NOMATCH$'
DSEG  ENDS

SSEG SEGMENT;堆栈段
   DW 64 DUP(?)
SSEG  ENDS

CSEG  SEGMENT;代码段
		ASSUME  CS:CSEG,SS:SSEG
START:	MOV  AX,DSEG
		MOV  DS,AX
		MOV  AX,SSEG
		MOV  SS,AX
		XOR AX,AX
		XOR SI,SI
MAINLOP:	MOV AL,DS:[STRING1+SI] ;两个字符串必须长度相等且以$结尾
			CMP AL,DS:[STRING2+SI]
			JNE NOMATCH
			CMP AL,'$'
			JE MATCH
			INC SI
			JMP MAINLOP
NOMATCH:	LEA DX,NOMATCHSTR
			MOV AH,9H
			INT 21H
			JMP HALT
MATCH:		LEA DX,MATCHSTR
			MOV AH,9H
			INT 21H
			JMP HALT
HALT:	MOV  AH,4CH
		INT  21H
CSEG ENDS
END START