DSEG SEGMENT;数据段
	BUFF DW 100,99,98,97,150,95,94,93,92,91,44,89,88,87,152,85 ;此处的BUFF即为题目中的DATA
	;由于100DH太大，这里用10H的字数组代替
	;注意：BUFF中必须至少有一个偶数
	NUMIDX DW 1,10,100,1000,10000
DSEG  ENDS

SSEG SEGMENT;堆栈段
   DW 64 DUP(?)
SSEG  ENDS

CSEG  SEGMENT;代码段
		ASSUME  CS:CSEG,DS:DSEG,SS:SSEG

SHOWNUM	PROC FAR ;此函数用于向屏幕输出一个0~65535的十进制数AX
		PUSH CX
		PUSH BX
		PUSH DX
		PUSH SI
		XOR DX,DX
		MOV BX,AX
		MOV CX,5H
INT2ASC:	MOV SI,CX
			DEC SI
			ADD SI,SI
			MOV AX,BX
			DIV WORD PTR DS:[NUMIDX+SI]
			PUSH AX
			XOR DX,DX
			MOV DL,AL
			ADD DL,30H
			MOV AH,02H
			INT 21H
			POP AX
			MUL WORD PTR DS:[NUMIDX+SI]
			SUB BX,AX
			LOOP INT2ASC
		XOR AX,AX
		POP SI
		POP DX
		POP BX
		POP CX
		RET
SHOWNUM ENDP

START:	MOV  AX,DSEG;
		MOV  DS,AX
		MOV  AX,SSEG
		MOV  SS,AX
		MOV CX,10H ;遍历整个数组
		XOR SI,SI
		MOV DX,0FFFFH
MAINLOP:	MOV AX,DS:[BUFF+SI]
			ADD SI,02H
			MOV BX,AX
			AND BX,01H ;判断是不是偶数
			CMP BX,1
			JZ LOOPEND
			CMP DX,AX
			JB LOOPEND ;判断是不是当前最小
			MOV DX,AX
LOOPEND:	LOOP MAINLOP
		MOV AX,DX ;结果保存在AX中
		CALL SHOWNUM;输出结果
		MOV AH,4CH
		INT 21H
CSEG ENDS
END START