DSEG SEGMENT;数据段
	HEXNUMIDX DW 1H,10H,100H,1000H
	INPUTTIP DB 'Please input a hex number:$'
	OUTPUTTIP DB 'The binary code of this number is:$'
	INPUTBUFF DB 0F0H
			  DB ?
			  DB 0F0H DUP(?)
DSEG  ENDS

SSEG SEGMENT;堆栈段
   DW 64 DUP(?)
SSEG  ENDS

CSEG  SEGMENT;代码段
		ASSUME  CS:CSEG,DS:DSEG,SS:SSEG

GETHEX	PROC FAR ;此函数用于从键盘获取一个0~FFFFH的16进制数，并存储到AX中
		XOR AX,AX
		PUSH CX
		PUSH BX
		PUSH DX
		PUSH SI
		LEA DX,INPUTBUFF
		MOV AH,0AH
		INT 21H
		XOR CX,CX
		MOV CL,DS:[INPUTBUFF+1]
		MOV BX,2 ;从偏移为2开始
		XOR DX,DX
ASC2HEX:	XOR AX,AX
			MOV AL,DS:[INPUTBUFF+BX]
			CMP AX,61H
			JAE LOWCHAR
			CMP AX,41H
			JAE UPCHAR
			SUB AX,30H ;处理数字
			JMP NEXT
UPCHAR:		SUB AX,037H ;处理大写字符
			JMP NEXT
LOWCHAR:	SUB AX,057H ;处理小写字符
			JMP NEXT
NEXT:		MOV SI,CX
			DEC SI
			ADD SI,SI
			PUSH DX
			MUL WORD PTR DS:[HEXNUMIDX+SI]
			POP DX
			ADD DX,AX
			INC BX
			LOOP ASC2HEX
		MOV AX,DX
		PUSH AX
		MOV DL,0AH
		MOV AH,02H
		INT 21H
		POP AX
		POP SI
		POP DX
		POP BX
		POP CX
		RET
GETHEX ENDP

PUTBIN	PROC FAR ;此函数用于向屏幕输出一个二进制数AX
		PUSH CX
		PUSH DX
		MOV CX,10H
SHOWBIN:	SHL AX,01H
			JB PUT1
			MOV DL,'0'
			JMP PUTEND
PUT1:		MOV DL,'1'
PUTEND:		PUSH AX
			MOV AH,02H
			INT 21H
			POP AX
			LOOP SHOWBIN
		POP DX
		POP CX
		RET
PUTBIN	ENDP

START:	MOV  AX,DSEG
		MOV  DS,AX
		MOV  AX,SSEG
		MOV  SS,AX
		LEA DX,INPUTTIP
		MOV AH,9H
		INT 21H
		CALL GETHEX
		PUSH AX
		LEA DX,OUTPUTTIP
		MOV AH,9H
		INT 21H
		POP AX
		CALL PUTBIN
		MOV  AH,4CH;程序结束
		INT  21H
CSEG ENDS
END START