DSEG SEGMENT;数据段
	INPUTTIP DB 'Please input a string:$'
	OUTPUTTIP DB 'After reverse:$'
	INPUTBUFF DB 0F0H
			  DB ?
			  DB 0F0H DUP(?)
DSEG  ENDS

SSEG SEGMENT;堆栈段
   DW 0F0H DUP(?)
SSEG  ENDS

CSEG  SEGMENT;代码段
		ASSUME  CS:CSEG,DS:DSEG,SS:SSEG

SHOW	MACRO TEXTBUFF ;此宏用于向屏幕输出一个字符串TEXTBUFF
		PUSH AX
		PUSH DX
		LEA DX,TEXTBUFF
		MOV AH,9H
		INT 21H
		POP DX
		POP AX
ENDM

GET	MACRO TEXTBUFF ;此宏用于向键盘获取一个字符串TEXTBUFF
		PUSH AX
		PUSH DX
		LEA DX,TEXTBUFF
		MOV AH,0AH
		INT 21H
		POP DX
		POP AX
ENDM

REVERSE	PROC FAR ;此函数用于反转字符串INPUTBUFF
		PUSH AX
		PUSH CX
		PUSH BX
		PUSH DX
		XOR DX,DX
		XOR AX,AX
		XOR CX,CX
		MOV CL,DS:[INPUTBUFF+1]
		MOV BX,2 ;从偏移为2开始
READ:	XOR AX,AX
		MOV AL,DS:[INPUTBUFF+BX]
		PUSH AX
		INC BX
		LOOP READ
		XOR CX,CX
		MOV CL,DS:[INPUTBUFF+1]
		MOV BX,2
WRITE:	XOR AX,AX
		POP AX
		MOV DS:[INPUTBUFF+BX],AL
		INC BX
		LOOP WRITE
		MOV DS:[INPUTBUFF+BX],'$'
		XOR AX,AX
		POP DX
		POP BX
		POP CX
		POP AX
		RET
REVERSE ENDP

START:	MOV  AX,DSEG;设定数据段
		MOV  DS,AX
		MOV  AX,SSEG;设定堆栈段
		MOV  SS,AX
		SHOW INPUTTIP
		GET INPUTBUFF
		CALL REVERSE
		MOV DL,0AH
		MOV AH,02H
		INT 21H
		SHOW OUTPUTTIP
		SHOW INPUTBUFF+2
		MOV  AH,4CH;程序结束
		INT  21H
CSEG ENDS
END START